## Slicing Strings

In [1]:
element = 'oxygen'
print('first three characters:', element[0:3])
print('last three characters:',element[3:6])

first three characters: oxy
last three characters: gen


In [2]:
element[:4]

'oxyg'

In [3]:
element[4:]

'en'

In [4]:
element[:]

'oxygen'

In [5]:
#1. The colon creates a sequence of indices starting at the first number and ending before
#   the second number. If the first or second number doesn't get specify then the colon
#   operator returns all the indices starting or ending at that point. 
#   The value of element[:4] is from the start to character 4.
#   The value of element[4:] is from character 4 to the end.
#   The value of element[:] takes the whole word.

In [6]:
element[-1]

'n'

In [7]:
element[-2]

'e'

In [8]:
#2. The negative numbers can be use to index from the end of the word.
#   The value of element[-1] gives the last character of the word oxygen.
#   The value of element[-2] gives the second to last character of the word oxygen.

In [9]:
element[1:-1]

'xyge'

In [10]:
#3. The value of element[1:-1] gives all of the characters in the word oxygen excluding
#   the first and last characters.

In [13]:
element [3:3]

''

In [18]:
import numpy

data = numpy.loadtxt(fname='inflammation-01.csv', delimiter=',')
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]]


In [52]:
extracted = data[3:3, 4:4]
print(extracted)

[]


In [29]:
data[3:3, 4:4]

array([], shape=(0, 0), dtype=float64)

In [28]:
data[3:3, :]

array([], shape=(0, 40), dtype=float64)

In [30]:
extracted_2 = data[3:3, :]
print(extracted_2)

[]


In [31]:
#4. The command data[3:3, 4:4] produce an empty array because [3:3] is asking
#   to take numbers starting from number 3 and ending at number 3, and same with [4:4].
#   Indices are whole numbers so we cannot ask to extract decimal numbers. The command
#   [3:3] is not grabbing any indices from the row and the command [4:4] is not grabbing
#   any indices from the column.
#   The command data[3:3, :] also gives an empty array because the [3:3] is not grabbing 
#   anything from the row. While the [:] grabs all of the indices in the column. The 
#   shape=(0,40) shows that there are zero indices grabbed from the row and 40 indices 
#   grabbed from the column.

## Stacking Arrays

In [32]:
import numpy

A = numpy.array([[1,2,3],[4,5,6],[7,8,9]])
print('A = ')
print(A)

B = numpy.hstack([A, A])
print('B = ')
print(B)

C = numpy.vstack([A, A])
print('C = ')
print(C)

A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
B = 
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
C = 
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


In [44]:
#vstack and hstack

slice_column = A[:, 0:1]
slice_column2 = A[:, 2:3]
print(slice_column)
print(slice_column2)

[[1]
 [4]
 [7]]
[[3]
 [6]
 [9]]


In [50]:
numpy.hstack((slice_column, slice_column2))

array([[1, 3],
       [4, 6],
       [7, 9]])

## Change In Inflammation

In [37]:
npdiff = numpy.array([ 0, 2, 5, 9, 14])

In [38]:
[2 - 0, 5 - 2, 9 - 5, 14 - 9]

[2, 3, 4, 5]

In [39]:
numpy.diff(npdiff)

array([2, 3, 4, 5])

In [57]:
whole_data = data[:]
print(whole_data.shape)

(54, 40)


In [62]:
new = numpy.diff(whole_data)

In [63]:
print(new.shape)

(54, 39)
