In [3]:
def fahr_to_celsius(temp):
    return((temp - 32) * (5/9))

In [4]:
fahr_to_celsius(70)

21.11111111111111

In [5]:
cel = fahr_to_celsius(70)

In [6]:
print(cel)

21.11111111111111


In [7]:
print('freezing point of water:', fahr_to_celsius(32), 'C')
print('boiling point of water:', fahr_to_celsius(212), 'C"')

freezing point of water: 0.0 C
boiling point of water: 100.0 C"


In [8]:
def celsius_to_kelvin(temp_c):
    return (temp_c + 273.15)

In [9]:
print('freezing point of water in kelvin:', celsius_to_kelvin(0.))

freezing point of water in kelvin: 273.15


In [10]:
#1st option, longer, might be easier to understand
def fahr_to_kelvin(temp_f):
    temp_c = fahr_to_celsius(temp_f)
    temp_k = celsius_to_kelvin(temp_c)
    return temp_k


In [11]:
print('boiling point of water in Kelvin:', fahr_to_kelvin(212.0))

boiling point of water in Kelvin: 373.15


In [12]:
#2nd option, cleaner/shorter code
def fahr_to_kelvin_cond(temp_f):
    return(celsius_to_kelvin(fahr_to_celsius(temp_f)))

In [13]:
#same output as above
print('boiling point of water in Kelvin:', fahr_to_kelvin_cond(212.0))

boiling point of water in Kelvin: 373.15


In [21]:
#end goal: visualize('inflammation-01.csv',',')
#visualize('inflammation-01.csv')
def visualize(filename, delim=','):
    #goal: createa function that will do the following steps:
    #1) read in the data file
    data = numpy.loadtxt(frame=filename, delimiter=delim)
    
    #2) create our 3 subplot holders with the empty figure
    fig = matplotlib.pyplot.figure(figsize=(10.0,3.0))
    axes1 = fig.add_subplot(1, 3, 1)
    axes2 = fig.add_subplot(1, 3, 2)
    axes3 = fig.add_subplot(1, 3, 3)
    
    #3) plot each of them
    axes1.set_ylabel('average')
    axes1.plot(numpy.mean(data, axis=0))
    
    axes2.set_ylabel('max')
    axes2.plot(numpy.max(data, axis=0))
    
    axes3.set_ylabel('min')
    axes3.plot(numpy.min(data,axis=0))
    
    #4) we want to show the plot
    fig.tight_layout()
    matplotlib.pyplot.show()

In [22]:
import numpy
import matplotlib.pyplot

In [23]:
visualize('inflammation-01.csv')

TypeError: loadtxt() got an unexpected keyword argument 'frame'

In [26]:
import glob
filenames = sorted(glob.glob('inflammation.csv'))

In [27]:
print(filenames)

[]


In [28]:
#let's create a for loop that would run through the enire filelist and will plot the 3
#panel figure for each inflammation data file
for files in filenames:
    print(files)
    visualize(files)

## Testing, Debugging, and Documenting Functions

In [38]:
#offset_mean(data, target_mean_value)
#returns a new array containing the original data with its mean offset
#to match the desired value
def offset_mean(data, target_mean_value):
     return (data - numpy.mean(data)) + target_mean_value
    
    '''Return a new arrays = containing the original data with its mean offset to match
    the desired value, (0 by default)
    
    Parameters
    ---------
    @param data an n-dimensional array of values
    @param target_mean_value the value you want to offset by (0 by default)
    @return a new array containing the original data with its mean offset to match the 
    desired value
    
    Examples
    --------
    >>> offset_mean([1,2,3])
    array([-1.,0.,1.])'''


In [36]:
help(numpy.loadtxt)

Help on function loadtxt in module numpy:

loadtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0, encoding='bytes', max_rows=None)
    Load data from a text file.
    
    Each row in the text file must have the same number of values.
    
    Parameters
    ----------
    fname : file, str, or pathlib.Path
        File, filename, or generator to read.  If the filename extension is
        ``.gz`` or ``.bz2``, the file is first decompressed. Note that
        generators should return byte strings for Python 3k.
    dtype : data-type, optional
        Data-type of the resulting array; default: float.  If this is a
        structured data-type, the resulting array will be 1-dimensional, and
        each row will be interpreted as an element of the array.  In this
        case, the number of columns used must match the number of fields in
        the data-type.
    comments : str or sequence of str, optional
  

In [30]:
#print an empty matrix of zeros
z = numpy.zeros((2,2))

In [31]:
print(z)

[[0. 0.]
 [0. 0.]]


In [32]:
print(offset_mean(z, 3))

[[3. 3.]
 [3. 3.]]


In [34]:
data = numpy.loadtxt(frame='inflammation-01.csv', delimiter=',')
offset_inflammation = offset_mean(data, 12)
print(offset_inflmmation)

TypeError: loadtxt() got an unexpected keyword argument 'frame'

In [35]:
print('std before and after offsets:', numpy.std(data), numpy.std(offset_inflmmation))

NameError: name 'data' is not defined